//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.25 at 09:20:21 PM CEST 
//


package org.agorava.xing.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}qualifications"/>
 *         &lt;element ref="{}schools"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qualifications",
    "schools"
})
@XmlRootElement(name = "educational_background")
public class EducationalBackground {

    @XmlElement(required = true)
    protected Qualifications qualifications;
    @XmlElement(required = true)
    protected Schools schools;

    /**
     * Gets the value of the qualifications property.
     * 
     * @return
     *     possible object is
     *     {@link Qualifications }
     *     
     */
    public Qualifications getQualifications() {
        return qualifications;
    }

    /**
     * Sets the value of the qualifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link Qualifications }
     *     
     */
    public void setQualifications(Qualifications value) {
        this.qualifications = value;
    }

    /**
     * Gets the value of the schools property.
     * 
     * @return
     *     possible object is
     *     {@link Schools }
     *     
     */
    public Schools getSchools() {
        return schools;
    }

    /**
     * Sets the value of the schools property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schools }
     *     
     */
    public void setSchools(Schools value) {
        this.schools = value;
    }

}
