//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.25 at 09:20:21 PM CEST 
//


package org.agorava.xing.jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.agorava.xing.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Interests_QNAME = new QName("", "interests");
    private final static QName _Tag_QNAME = new QName("", "tag");
    private final static QName _MiniThumb_QNAME = new QName("", "mini_thumb");
    private final static QName _Icq_QNAME = new QName("", "icq");
    private final static QName _City_QNAME = new QName("", "city");
    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _FirstName_QNAME = new QName("", "first_name");
    private final static QName _Qualification_QNAME = new QName("", "qualification");
    private final static QName _Title_QNAME = new QName("", "title");
    private final static QName _MobilePhone_QNAME = new QName("", "mobile_phone");
    private final static QName _DateAwarded_QNAME = new QName("", "date_awarded");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Province_QNAME = new QName("", "province");
    private final static QName _Gender_QNAME = new QName("", "gender");
    private final static QName _Year_QNAME = new QName("", "year");
    private final static QName _Industry_QNAME = new QName("", "industry");
    private final static QName _Msn_QNAME = new QName("", "msn");
    private final static QName _EmploymentStatus_QNAME = new QName("", "employment_status");
    private final static QName _Haves_QNAME = new QName("", "haves");
    private final static QName _MediumThumb_QNAME = new QName("", "medium_thumb");
    private final static QName _Wants_QNAME = new QName("", "wants");
    private final static QName _Country_QNAME = new QName("", "country");
    private final static QName _UtcOffset_QNAME = new QName("", "utc_offset");
    private final static QName _DisplayName_QNAME = new QName("", "display_name");
    private final static QName _ActiveEmail_QNAME = new QName("", "active_email");
    private final static QName _CompanySize_QNAME = new QName("", "company_size");
    private final static QName _Permalink_QNAME = new QName("", "permalink");
    private final static QName _MaxiThumb_QNAME = new QName("", "maxi_thumb");
    private final static QName _Email_QNAME = new QName("", "email");
    private final static QName _LastName_QNAME = new QName("", "last_name");
    private final static QName _Month_QNAME = new QName("", "month");
    private final static QName _OrganisationMember_QNAME = new QName("", "organisation_member");
    private final static QName _Day_QNAME = new QName("", "day");
    private final static QName _PageName_QNAME = new QName("", "page_name");
    private final static QName _Thumb_QNAME = new QName("", "thumb");
    private final static QName _Large_QNAME = new QName("", "large");
    private final static QName _Skype_QNAME = new QName("", "skype");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.agorava.xing.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PhotoUrls }
     * 
     */
    public PhotoUrls createPhotoUrls() {
        return new PhotoUrls();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link Users }
     * 
     */
    public Users createUsers() {
        return new Users();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link BirthDate }
     * 
     */
    public BirthDate createBirthDate() {
        return new BirthDate();
    }

    /**
     * Create an instance of {@link TimeZone }
     * 
     */
    public TimeZone createTimeZone() {
        return new TimeZone();
    }

    /**
     * Create an instance of {@link PremiumServices }
     * 
     */
    public PremiumServices createPremiumServices() {
        return new PremiumServices();
    }

    /**
     * Create an instance of {@link Badges }
     * 
     */
    public Badges createBadges() {
        return new Badges();
    }

    /**
     * Create an instance of {@link Languages }
     * 
     */
    public Languages createLanguages() {
        return new Languages();
    }

    /**
     * Create an instance of {@link En }
     * 
     */
    public En createEn() {
        return new En();
    }

    /**
     * Create an instance of {@link Fr }
     * 
     */
    public Fr createFr() {
        return new Fr();
    }

    /**
     * Create an instance of {@link De }
     * 
     */
    public De createDe() {
        return new De();
    }

    /**
     * Create an instance of {@link PrivateAddress }
     * 
     */
    public PrivateAddress createPrivateAddress() {
        return new PrivateAddress();
    }

    /**
     * Create an instance of {@link Street }
     * 
     */
    public Street createStreet() {
        return new Street();
    }

    /**
     * Create an instance of {@link ZipCode }
     * 
     */
    public ZipCode createZipCode() {
        return new ZipCode();
    }

    /**
     * Create an instance of {@link Fax }
     * 
     */
    public Fax createFax() {
        return new Fax();
    }

    /**
     * Create an instance of {@link BusinessAddress }
     * 
     */
    public BusinessAddress createBusinessAddress() {
        return new BusinessAddress();
    }

    /**
     * Create an instance of {@link WebProfiles }
     * 
     */
    public WebProfiles createWebProfiles() {
        return new WebProfiles();
    }

    /**
     * Create an instance of {@link Blog }
     * 
     */
    public Blog createBlog() {
        return new Blog();
    }

    /**
     * Create an instance of {@link InstantMessagingAccounts }
     * 
     */
    public InstantMessagingAccounts createInstantMessagingAccounts() {
        return new InstantMessagingAccounts();
    }

    /**
     * Create an instance of {@link ProfessionalExperience }
     * 
     */
    public ProfessionalExperience createProfessionalExperience() {
        return new ProfessionalExperience();
    }

    /**
     * Create an instance of {@link PrimaryCompany }
     * 
     */
    public PrimaryCompany createPrimaryCompany() {
        return new PrimaryCompany();
    }

    /**
     * Create an instance of {@link Url }
     * 
     */
    public Url createUrl() {
        return new Url();
    }

    /**
     * Create an instance of {@link CareerLevel }
     * 
     */
    public CareerLevel createCareerLevel() {
        return new CareerLevel();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link BeginDate }
     * 
     */
    public BeginDate createBeginDate() {
        return new BeginDate();
    }

    /**
     * Create an instance of {@link EndDate }
     * 
     */
    public EndDate createEndDate() {
        return new EndDate();
    }

    /**
     * Create an instance of {@link NonPrimaryCompanies }
     * 
     */
    public NonPrimaryCompanies createNonPrimaryCompanies() {
        return new NonPrimaryCompanies();
    }

    /**
     * Create an instance of {@link NonPrimaryCompany }
     * 
     */
    public NonPrimaryCompany createNonPrimaryCompany() {
        return new NonPrimaryCompany();
    }

    /**
     * Create an instance of {@link Awards }
     * 
     */
    public Awards createAwards() {
        return new Awards();
    }

    /**
     * Create an instance of {@link Award }
     * 
     */
    public Award createAward() {
        return new Award();
    }

    /**
     * Create an instance of {@link EducationalBackground }
     * 
     */
    public EducationalBackground createEducationalBackground() {
        return new EducationalBackground();
    }

    /**
     * Create an instance of {@link Qualifications }
     * 
     */
    public Qualifications createQualifications() {
        return new Qualifications();
    }

    /**
     * Create an instance of {@link Schools }
     * 
     */
    public Schools createSchools() {
        return new Schools();
    }

    /**
     * Create an instance of {@link School }
     * 
     */
    public School createSchool() {
        return new School();
    }

    /**
     * Create an instance of {@link Notes }
     * 
     */
    public Notes createNotes() {
        return new Notes();
    }

    /**
     * Create an instance of {@link Subject }
     * 
     */
    public Subject createSubject() {
        return new Subject();
    }

    /**
     * Create an instance of {@link Degree }
     * 
     */
    public Degree createDegree() {
        return new Degree();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "interests")
    public JAXBElement<String> createInterests(String value) {
        return new JAXBElement<String>(_Interests_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tag")
    public JAXBElement<String> createTag(String value) {
        return new JAXBElement<String>(_Tag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mini_thumb")
    public JAXBElement<String> createMiniThumb(String value) {
        return new JAXBElement<String>(_MiniThumb_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "icq")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIcq(String value) {
        return new JAXBElement<String>(_Icq_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "city")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "first_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFirstName(String value) {
        return new JAXBElement<String>(_FirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "qualification")
    public JAXBElement<String> createQualification(String value) {
        return new JAXBElement<String>(_Qualification_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mobile_phone")
    public JAXBElement<String> createMobilePhone(String value) {
        return new JAXBElement<String>(_MobilePhone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date_awarded")
    public JAXBElement<BigInteger> createDateAwarded(BigInteger value) {
        return new JAXBElement<BigInteger>(_DateAwarded_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "province")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProvince(String value) {
        return new JAXBElement<String>(_Province_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gender")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGender(String value) {
        return new JAXBElement<String>(_Gender_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "year")
    public JAXBElement<BigInteger> createYear(BigInteger value) {
        return new JAXBElement<BigInteger>(_Year_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "industry")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIndustry(String value) {
        return new JAXBElement<String>(_Industry_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "msn")
    public JAXBElement<String> createMsn(String value) {
        return new JAXBElement<String>(_Msn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "employment_status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createEmploymentStatus(String value) {
        return new JAXBElement<String>(_EmploymentStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "haves")
    public JAXBElement<String> createHaves(String value) {
        return new JAXBElement<String>(_Haves_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "medium_thumb")
    public JAXBElement<String> createMediumThumb(String value) {
        return new JAXBElement<String>(_MediumThumb_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wants")
    public JAXBElement<String> createWants(String value) {
        return new JAXBElement<String>(_Wants_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "utc_offset")
    public JAXBElement<BigDecimal> createUtcOffset(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_UtcOffset_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "display_name")
    public JAXBElement<String> createDisplayName(String value) {
        return new JAXBElement<String>(_DisplayName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "active_email")
    public JAXBElement<String> createActiveEmail(String value) {
        return new JAXBElement<String>(_ActiveEmail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "company_size")
    public JAXBElement<String> createCompanySize(String value) {
        return new JAXBElement<String>(_CompanySize_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "permalink")
    public JAXBElement<String> createPermalink(String value) {
        return new JAXBElement<String>(_Permalink_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "maxi_thumb")
    public JAXBElement<String> createMaxiThumb(String value) {
        return new JAXBElement<String>(_MaxiThumb_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "last_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLastName(String value) {
        return new JAXBElement<String>(_LastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "month")
    public JAXBElement<BigInteger> createMonth(BigInteger value) {
        return new JAXBElement<BigInteger>(_Month_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "organisation_member")
    public JAXBElement<String> createOrganisationMember(String value) {
        return new JAXBElement<String>(_OrganisationMember_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "day")
    public JAXBElement<BigInteger> createDay(BigInteger value) {
        return new JAXBElement<BigInteger>(_Day_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "page_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPageName(String value) {
        return new JAXBElement<String>(_PageName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "thumb")
    public JAXBElement<String> createThumb(String value) {
        return new JAXBElement<String>(_Thumb_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "large")
    public JAXBElement<String> createLarge(String value) {
        return new JAXBElement<String>(_Large_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "skype")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSkype(String value) {
        return new JAXBElement<String>(_Skype_QNAME, String.class, null, value);
    }

}
