//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.25 at 09:20:21 PM CEST 
//


package org.agorava.xing.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}large"/>
 *         &lt;element ref="{}maxi_thumb"/>
 *         &lt;element ref="{}medium_thumb"/>
 *         &lt;element ref="{}mini_thumb"/>
 *         &lt;element ref="{}thumb"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "large",
    "maxiThumb",
    "mediumThumb",
    "miniThumb",
    "thumb"
})
@XmlRootElement(name = "photo_urls")
public class PhotoUrls {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String large;
    @XmlElement(name = "maxi_thumb", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String maxiThumb;
    @XmlElement(name = "medium_thumb", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String mediumThumb;
    @XmlElement(name = "mini_thumb", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String miniThumb;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String thumb;

    /**
     * Gets the value of the large property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLarge() {
        return large;
    }

    /**
     * Sets the value of the large property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLarge(String value) {
        this.large = value;
    }

    /**
     * Gets the value of the maxiThumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxiThumb() {
        return maxiThumb;
    }

    /**
     * Sets the value of the maxiThumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxiThumb(String value) {
        this.maxiThumb = value;
    }

    /**
     * Gets the value of the mediumThumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediumThumb() {
        return mediumThumb;
    }

    /**
     * Sets the value of the mediumThumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediumThumb(String value) {
        this.mediumThumb = value;
    }

    /**
     * Gets the value of the miniThumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiniThumb() {
        return miniThumb;
    }

    /**
     * Sets the value of the miniThumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiniThumb(String value) {
        this.miniThumb = value;
    }

    /**
     * Gets the value of the thumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThumb() {
        return thumb;
    }

    /**
     * Sets the value of the thumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThumb(String value) {
        this.thumb = value;
    }

}
