//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.25 at 09:20:21 PM CEST 
//


package org.agorava.xing.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}primary_company"/>
 *         &lt;element ref="{}non_primary_companies"/>
 *         &lt;element ref="{}awards"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "primaryCompany",
    "nonPrimaryCompanies",
    "awards"
})
@XmlRootElement(name = "professional_experience")
public class ProfessionalExperience {

    @XmlElement(name = "primary_company", required = true)
    protected PrimaryCompany primaryCompany;
    @XmlElement(name = "non_primary_companies", required = true)
    protected NonPrimaryCompanies nonPrimaryCompanies;
    @XmlElement(required = true)
    protected Awards awards;

    /**
     * Gets the value of the primaryCompany property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryCompany }
     *     
     */
    public PrimaryCompany getPrimaryCompany() {
        return primaryCompany;
    }

    /**
     * Sets the value of the primaryCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryCompany }
     *     
     */
    public void setPrimaryCompany(PrimaryCompany value) {
        this.primaryCompany = value;
    }

    /**
     * Gets the value of the nonPrimaryCompanies property.
     * 
     * @return
     *     possible object is
     *     {@link NonPrimaryCompanies }
     *     
     */
    public NonPrimaryCompanies getNonPrimaryCompanies() {
        return nonPrimaryCompanies;
    }

    /**
     * Sets the value of the nonPrimaryCompanies property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonPrimaryCompanies }
     *     
     */
    public void setNonPrimaryCompanies(NonPrimaryCompanies value) {
        this.nonPrimaryCompanies = value;
    }

    /**
     * Gets the value of the awards property.
     * 
     * @return
     *     possible object is
     *     {@link Awards }
     *     
     */
    public Awards getAwards() {
        return awards;
    }

    /**
     * Sets the value of the awards property.
     * 
     * @param value
     *     allowed object is
     *     {@link Awards }
     *     
     */
    public void setAwards(Awards value) {
        this.awards = value;
    }

}
