//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.25 at 09:20:21 PM CEST 
//


package org.agorava.xing.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}id"/>
 *         &lt;element ref="{}first_name"/>
 *         &lt;element ref="{}last_name"/>
 *         &lt;element ref="{}display_name"/>
 *         &lt;element ref="{}page_name"/>
 *         &lt;element ref="{}employment_status"/>
 *         &lt;element ref="{}gender"/>
 *         &lt;element ref="{}birth_date"/>
 *         &lt;element ref="{}active_email"/>
 *         &lt;element ref="{}time_zone"/>
 *         &lt;element ref="{}premium_services"/>
 *         &lt;element ref="{}badges"/>
 *         &lt;element ref="{}wants"/>
 *         &lt;element ref="{}haves"/>
 *         &lt;element ref="{}interests"/>
 *         &lt;element ref="{}organisation_member"/>
 *         &lt;element ref="{}languages"/>
 *         &lt;element ref="{}private_address"/>
 *         &lt;element ref="{}business_address"/>
 *         &lt;element ref="{}web_profiles"/>
 *         &lt;element ref="{}instant_messaging_accounts"/>
 *         &lt;element ref="{}professional_experience"/>
 *         &lt;element ref="{}educational_background"/>
 *         &lt;element ref="{}photo_urls"/>
 *         &lt;element ref="{}permalink"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "firstName",
    "lastName",
    "displayName",
    "pageName",
    "employmentStatus",
    "gender",
    "birthDate",
    "activeEmail",
    "timeZone",
    "premiumServices",
    "badges",
    "wants",
    "haves",
    "interests",
    "organisationMember",
    "languages",
    "privateAddress",
    "businessAddress",
    "webProfiles",
    "instantMessagingAccounts",
    "professionalExperience",
    "educationalBackground",
    "photoUrls",
    "permalink"
})
@XmlRootElement(name = "user")
public class User {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String id;
    @XmlElement(name = "first_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String firstName;
    @XmlElement(name = "last_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String lastName;
    @XmlElement(name = "display_name", required = true)
    protected String displayName;
    @XmlElement(name = "page_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pageName;
    @XmlElement(name = "employment_status", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String employmentStatus;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String gender;
    @XmlElement(name = "birth_date", required = true)
    protected BirthDate birthDate;
    @XmlElement(name = "active_email", required = true)
    protected String activeEmail;
    @XmlElement(name = "time_zone", required = true)
    protected TimeZone timeZone;
    @XmlElement(name = "premium_services", required = true)
    protected PremiumServices premiumServices;
    @XmlElement(required = true)
    protected Badges badges;
    @XmlElement(required = true)
    protected String wants;
    @XmlElement(required = true)
    protected String haves;
    @XmlElement(required = true)
    protected String interests;
    @XmlElement(name = "organisation_member", required = true)
    protected String organisationMember;
    @XmlElement(required = true)
    protected Languages languages;
    @XmlElement(name = "private_address", required = true)
    protected PrivateAddress privateAddress;
    @XmlElement(name = "business_address", required = true)
    protected BusinessAddress businessAddress;
    @XmlElement(name = "web_profiles", required = true)
    protected WebProfiles webProfiles;
    @XmlElement(name = "instant_messaging_accounts", required = true)
    protected InstantMessagingAccounts instantMessagingAccounts;
    @XmlElement(name = "professional_experience", required = true)
    protected ProfessionalExperience professionalExperience;
    @XmlElement(name = "educational_background", required = true)
    protected EducationalBackground educationalBackground;
    @XmlElement(name = "photo_urls", required = true)
    protected PhotoUrls photoUrls;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String permalink;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the pageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageName() {
        return pageName;
    }

    /**
     * Sets the value of the pageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageName(String value) {
        this.pageName = value;
    }

    /**
     * Gets the value of the employmentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentStatus() {
        return employmentStatus;
    }

    /**
     * Sets the value of the employmentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentStatus(String value) {
        this.employmentStatus = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link BirthDate }
     *     
     */
    public BirthDate getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BirthDate }
     *     
     */
    public void setBirthDate(BirthDate value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the activeEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveEmail() {
        return activeEmail;
    }

    /**
     * Sets the value of the activeEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveEmail(String value) {
        this.activeEmail = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link TimeZone }
     *     
     */
    public TimeZone getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeZone }
     *     
     */
    public void setTimeZone(TimeZone value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the premiumServices property.
     * 
     * @return
     *     possible object is
     *     {@link PremiumServices }
     *     
     */
    public PremiumServices getPremiumServices() {
        return premiumServices;
    }

    /**
     * Sets the value of the premiumServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link PremiumServices }
     *     
     */
    public void setPremiumServices(PremiumServices value) {
        this.premiumServices = value;
    }

    /**
     * Gets the value of the badges property.
     * 
     * @return
     *     possible object is
     *     {@link Badges }
     *     
     */
    public Badges getBadges() {
        return badges;
    }

    /**
     * Sets the value of the badges property.
     * 
     * @param value
     *     allowed object is
     *     {@link Badges }
     *     
     */
    public void setBadges(Badges value) {
        this.badges = value;
    }

    /**
     * Gets the value of the wants property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWants() {
        return wants;
    }

    /**
     * Sets the value of the wants property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWants(String value) {
        this.wants = value;
    }

    /**
     * Gets the value of the haves property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaves() {
        return haves;
    }

    /**
     * Sets the value of the haves property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaves(String value) {
        this.haves = value;
    }

    /**
     * Gets the value of the interests property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterests() {
        return interests;
    }

    /**
     * Sets the value of the interests property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterests(String value) {
        this.interests = value;
    }

    /**
     * Gets the value of the organisationMember property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganisationMember() {
        return organisationMember;
    }

    /**
     * Sets the value of the organisationMember property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganisationMember(String value) {
        this.organisationMember = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * @return
     *     possible object is
     *     {@link Languages }
     *     
     */
    public Languages getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Languages }
     *     
     */
    public void setLanguages(Languages value) {
        this.languages = value;
    }

    /**
     * Gets the value of the privateAddress property.
     * 
     * @return
     *     possible object is
     *     {@link PrivateAddress }
     *     
     */
    public PrivateAddress getPrivateAddress() {
        return privateAddress;
    }

    /**
     * Sets the value of the privateAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivateAddress }
     *     
     */
    public void setPrivateAddress(PrivateAddress value) {
        this.privateAddress = value;
    }

    /**
     * Gets the value of the businessAddress property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessAddress }
     *     
     */
    public BusinessAddress getBusinessAddress() {
        return businessAddress;
    }

    /**
     * Sets the value of the businessAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessAddress }
     *     
     */
    public void setBusinessAddress(BusinessAddress value) {
        this.businessAddress = value;
    }

    /**
     * Gets the value of the webProfiles property.
     * 
     * @return
     *     possible object is
     *     {@link WebProfiles }
     *     
     */
    public WebProfiles getWebProfiles() {
        return webProfiles;
    }

    /**
     * Sets the value of the webProfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebProfiles }
     *     
     */
    public void setWebProfiles(WebProfiles value) {
        this.webProfiles = value;
    }

    /**
     * Gets the value of the instantMessagingAccounts property.
     * 
     * @return
     *     possible object is
     *     {@link InstantMessagingAccounts }
     *     
     */
    public InstantMessagingAccounts getInstantMessagingAccounts() {
        return instantMessagingAccounts;
    }

    /**
     * Sets the value of the instantMessagingAccounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstantMessagingAccounts }
     *     
     */
    public void setInstantMessagingAccounts(InstantMessagingAccounts value) {
        this.instantMessagingAccounts = value;
    }

    /**
     * Gets the value of the professionalExperience property.
     * 
     * @return
     *     possible object is
     *     {@link ProfessionalExperience }
     *     
     */
    public ProfessionalExperience getProfessionalExperience() {
        return professionalExperience;
    }

    /**
     * Sets the value of the professionalExperience property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfessionalExperience }
     *     
     */
    public void setProfessionalExperience(ProfessionalExperience value) {
        this.professionalExperience = value;
    }

    /**
     * Gets the value of the educationalBackground property.
     * 
     * @return
     *     possible object is
     *     {@link EducationalBackground }
     *     
     */
    public EducationalBackground getEducationalBackground() {
        return educationalBackground;
    }

    /**
     * Sets the value of the educationalBackground property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationalBackground }
     *     
     */
    public void setEducationalBackground(EducationalBackground value) {
        this.educationalBackground = value;
    }

    /**
     * Gets the value of the photoUrls property.
     * 
     * @return
     *     possible object is
     *     {@link PhotoUrls }
     *     
     */
    public PhotoUrls getPhotoUrls() {
        return photoUrls;
    }

    /**
     * Sets the value of the photoUrls property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhotoUrls }
     *     
     */
    public void setPhotoUrls(PhotoUrls value) {
        this.photoUrls = value;
    }

    /**
     * Gets the value of the permalink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPermalink() {
        return permalink;
    }

    /**
     * Sets the value of the permalink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPermalink(String value) {
        this.permalink = value;
    }

}
